name: Compile test

on:
  workflow_dispatch:

jobs:
  build-pr:
    strategy:
      fail-fast: true
      matrix:
        machine:
          - qcm6490-idp
          #- qcs6490-rb3gen2-core-kit
          #- sa8775p-ride-sx
    runs-on: [self-hosted, x86]
    name: ${{ matrix.machine }}/poky/systemd
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compile
        run: |
          # Use this directory to cache things. You can do something
          # like:
          #    if [ ! -d ${persist_dir}/sdk ] ;
          #       echo "Downloading sdk"
          #       .....
          #    fi
          persist_dir=/srv/gh-runners/quic-qrb-ros

          # quic-yocto uses Kas to build with:
          # export DL_DIR=${persist_dir}/downloads
          # export SSTATE_DIR=${persist_dir}/sstate-cache
          # mkdir -p $DL_DIR
          # mkdir -p $SSTATE_DIR
          # mkdir build
          # cd build
          # kas build ../ci/${{ matrix.machine }}.yml
